### ISSUE TITLE
Not being able to understand the purpose of peripheral.on method

### ISSUE THREAD

**Issue by mindteckarthita** [mybigday/react-native-multi-ble-peripheral#1]
We tried to use this package for connecting with central, but initially according to your usage document, there is an **peripheral.on** method is being fired from which other methods are being called.
Not being able to understand the purpose of this on method, not even found any definition of it in the code.
Not being able to use it, even if we try to call it in the same way according to your usage, nothing is being performed.

**Note ::** we are using it for iOS platform

**Comment by hans00** [comment]
That because we need wait manager ready before any other operation.
On iOS the manager need few time to wait state is ready, before it the operation will error.

https://github.com/mybigday/react-native-multi-ble-peripheral/blob/f51580957fdf05cfb32db432e8f99da97c3e7e85/ios/ReactNativeMultiBlePeripheral.swift#L65-L75
